### ISSUE TITLE
What is the actual minimal supported OSX version？

### ISSUE THREAD

**Issue by acely** [eko5624/mpv-macos-intel#3]
Hi, thanks for the build.
I noticed in build script says minimal macos version is 10.8 `CFLAGS: -mmacosx-version-min=10.8`
But in my macos 10.11 it failed to launch, with the following error:
```
Macbook:~ xxx$ /Users/xxx/Documents/All-in-One/mpv.app/Contents/MacOS/mpv ; exit;
dyld: Library not loaded: @executable_path/lib/libass.9.dylib
  Referenced from: /Users/xxx/Documents/All-in-One/mpv.app/Contents/MacOS/mpv
  Reason: no suitable image found.  Did find:
	/Users/xxx/Documents/All-in-One/mpv.app/Contents/MacOS/lib/libass.9.dylib: cannot load 'libass.9.dylib' (load command 0x80000034 is unknown)
	/Users/xxx/Documents/All-in-One/mpv.app/Contents/MacOS/lib/libass.9.dylib: cannot load 'libass.9.dylib' (load command 0x80000034 is unknown)
Trace/BPT trap: 5
logout
```

**Comment by eko5624** [comment]
which version of mpv do you use?

**Comment by acely** [comment]
Im using 2022-10-10 version

**Comment by acely** [comment]
I also tested the 2022-04-18 build (mpv-0.34.0-265-g305332f8a0), it also failed on macos 10.11
Errors:
`dyld: Library not loaded: /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer`

**Comment by eko5624** [comment]
what about his build?
https://github.com/NextFire/mpv-macos-git-builds/releases/tag/mpv-0.34.0-509-g59fc8eecbc

**Comment by acely** [comment]
> what about his build? https://github.com/NextFire/mpv-macos-git-builds/releases/tag/mpv-0.34.0-509-g59fc8eecbc

Also fails with error:
`dyld: Library not loaded: /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer`

I did some research and found [apple's doc](https://developer.apple.com/documentation/mediaplayer) for MediaPlay framework, lt says `macOS 10.12.1+`
![image](https://user-images.githubusercontent.com/5640723/195981551-e9d85a25-4f84-46d9-879f-cde378aac267.png)

Does this mean recent mpv requires at least 10.12?
And not possible to work on 10.11 any more?

**Comment by acely** [comment]
Actually it may possible to build for 10.11, I found [this issue](https://github.com/iina/iina/issues/1345) from IINA repo, which say MediaPlayer can be set as optional.

**Comment by eko5624** [comment]
@acely  Try this build. https://github.com/eko5624/mpv-macos-intel/releases/download/2023-02-20/mpv-test.zip

**Comment by acely** [comment]
Thanks, This build still not work in 10.11
```
Macbook:~ xxx$ /Users/xxx/Downloads/mpv-test/mpv.app/Contents/MacOS/mpv ; exit;
dyld: Symbol not found: _kCVImageBufferTransferFunction_ITU_R_2100_HLG
  Referenced from: /Users/xxx/Downloads/mpv-test/mpv.app/Contents/MacOS/lib/libavutil.58.dylib (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
 in /Users/xxx/Downloads/mpv-test/mpv.app/Contents/MacOS/lib/libavutil.58.dylib
Trace/BPT trap: 5
logout
```

**Comment by eko5624** [comment]
@acely  能否再帮我测试一下下面这个版本。编译用的SDK版本是12.3，设置了MACOSX_DEPLOYMENT_TARGET=10.11，并禁用了MediaPlayer。
https://github.com/eko5624/mpv-macos-intel/releases/download/2023-02-20/test-10.11.zip

**Comment by acely** [comment]
虽然还是打不开，但是感觉有戏了，不再是严重的框架级报错
这次只是报了libpng的错误
```
Macbook:~ xxx$ /Users/xxx/Downloads/0\ APPS/mpv.app/Contents/MacOS/mpv ; exit;
dyld: Library not loaded: @executable_path/lib/libpng16.16.dylib
  Referenced from: /Users/xxx/Downloads/0 APPS/mpv.app/Contents/MacOS/lib/libass.9.dylib
  Reason: no suitable image found.  Did find:
	/Users/xxx/Downloads/0 APPS/mpv.app/Contents/MacOS/lib/libpng16.16.dylib: cannot load 'libpng16.16.dylib' (load command 0x80000034 is unknown)
	/Users/xxx/Downloads/0 APPS/mpv.app/Contents/MacOS/lib/libpng16.16.dylib: cannot load 'libpng16.16.dylib' (load command 0x80000034 is unknown)
Trace/BPT trap: 5
```

**Comment by eko5624** [comment]
可能是编译用的SDK版本太高了。我尝试用10.11的SDK编译老是卡在libjxl的编译过程。提示：
/Users/runner/work/mpv-macos-intel/mpv-macos-intel/workspace/include/hwy/ops/shared-inl.h:37:1: warning: unsupported 'avxvnni' in the 'target' attribute string; 'target' attribute ignored [-Wignored-attributes]

编译日志：https://github.com/eko5624/mpv-macos-intel/actions/runs/4273517394

我google了一下这个avxvnni，一直没有找到解决方案。

**Comment by eko5624** [comment]
在这里记录一下。对所有的lib文件进行了兼容性检查，确实发现在了几个文件有兼容性问题。

命令：
```
cd /Applications/mpv.app/Contents/MacOS/lib
for f in *.dylib; do
  echo "check $f ================="
  otool -l $f | grep -E -A4 '(LC_VERSION_MIN_MACOSX|LC_BUILD_VERSION)' | grep -B1 sdk
done
```

结果：
```
check libSDL2-2.0.0.dylib =================
  version 10.11
      sdk 12.3
check libX11.6.dylib =================
    minos 13.0
      sdk 13.0
check libXau.6.dylib =================
    minos 13.0
      sdk 13.0
check libXdmcp.6.dylib =================
    minos 13.0
      sdk 13.0
check libass.9.dylib =================
  version 10.11
      sdk 12.3
check libavcodec.60.dylib =================
  version 10.11
      sdk 12.3
check libavdevice.60.dylib =================
  version 10.11
      sdk 12.3
check libavfilter.9.dylib =================
  version 10.11
      sdk 12.3
check libavformat.60.dylib =================
  version 10.11
      sdk 12.3
check libavutil.58.dylib =================
  version 10.11
      sdk 12.3
check libbluray.2.dylib =================
  version 10.11
      sdk 12.3
check libbrotlicommon.1.dylib =================
  version 10.11
      sdk 12.3
check libbrotlidec.1.dylib =================
  version 10.11
      sdk 12.3
check libbrotlienc.1.dylib =================
  version 10.11
      sdk 12.3
check libbs2b.0.dylib =================
  version 10.11
      sdk 12.3
check libcaca.0.dylib =================
  version 10.11
      sdk 12.3
check libcjson.1.dylib =================
    minos 13.0
      sdk 13.0
check libcrypto.1.1.dylib =================
  version 10.11
      sdk 12.3
check libdav1d.6.dylib =================
  version 10.11
      sdk 12.3
check libdavs2.16.dylib =================
  version 10.11
      sdk 12.3
check libfontconfig.1.dylib =================
  version 10.11
      sdk 12.3
check libfreetype.6.dylib =================
  version 10.11
      sdk 12.3
check libfribidi.0.dylib =================
  version 10.11
      sdk 12.3
check libharfbuzz.0.dylib =================
  version 10.11
      sdk 12.3
check libintl.8.dylib =================
    minos 13.0
      sdk 13.0
check libjpeg.8.dylib =================
  version 10.11
      sdk 12.3
check libjxl.0.9.dylib =================
  version 10.11
      sdk 12.3
check libjxl_threads.0.9.dylib =================
  version 10.11
      sdk 12.3
check liblcms2.2.dylib =================
  version 10.11
      sdk 12.3
check libluajit-5.1.2.dylib =================
  version 10.11
      sdk 12.3
check liblzma.5.dylib =================
  version 10.11
      sdk 12.3
check libmbedcrypto.13.dylib =================
    minos 13.0
      sdk 13.0
check libmodplug.1.dylib =================
  version 10.11
      sdk 12.3
check libmp3lame.0.dylib =================
  version 10.11
      sdk 12.3
check libmysofa.1.dylib =================
  version 10.11
      sdk 12.3
check libogg.0.dylib =================
  version 10.11
      sdk 12.3
check libopencore-amrnb.0.dylib =================
  version 10.11
      sdk 12.3
check libopencore-amrwb.0.dylib =================
  version 10.11
      sdk 12.3
check libopus.0.dylib =================
  version 10.11
      sdk 12.3
check libplacebo.252.dylib =================
  version 10.11
      sdk 12.3
check libpng16.16.dylib =================
    minos 13.0
      sdk 13.0
check libpostproc.57.dylib =================
  version 10.11
      sdk 12.3
check librist.4.dylib =================
  version 10.11
      sdk 12.3
check librubberband.2.dylib =================
  version 10.13
      sdk 12.3
check libsharpyuv.0.dylib =================
  version 10.11
      sdk 12.3
check libsnappy.1.dylib =================
  version 10.11
      sdk 12.3
check libsoxr.0.dylib =================
  version 10.11
      sdk 12.3
check libspeex.1.dylib =================
  version 10.11
      sdk 12.3
check libsrt.1.5.dylib =================
  version 10.11
      sdk 12.3
check libssh.4.dylib =================
  version 10.11
      sdk 12.3
check libssl.1.1.dylib =================
  version 10.11
      sdk 12.3
check libswiftAppKit.dylib =================
  version 10.9
      sdk 10.14
check libswiftCore.dylib =================
  version 10.9
      sdk 10.14
check libswiftCoreData.dylib =================
  version 10.9
      sdk 10.14
check libswiftCoreFoundation.dylib =================
  version 10.9
      sdk 10.14
check libswiftCoreGraphics.dylib =================
  version 10.9
      sdk 10.14
check libswiftCoreImage.dylib =================
  version 10.9
      sdk 10.14
check libswiftDarwin.dylib =================
  version 10.9
      sdk 10.14
check libswiftDispatch.dylib =================
  version 10.9
      sdk 10.14
check libswiftFoundation.dylib =================
  version 10.9
      sdk 10.14
check libswiftIOKit.dylib =================
  version 10.9
      sdk 10.14
check libswiftMetal.dylib =================
  version 10.9
      sdk 10.14
check libswiftObjectiveC.dylib =================
  version 10.9
      sdk 10.14
check libswiftQuartzCore.dylib =================
  version 10.9
      sdk 10.14
check libswiftXPC.dylib =================
  version 10.9
      sdk 10.14
check libswiftos.dylib =================
  version 10.9
      sdk 10.14
check libswresample.4.dylib =================
  version 10.11
      sdk 12.3
check libswscale.7.dylib =================
  version 10.11
      sdk 12.3
check libtheoradec.1.dylib =================
  version 10.11
      sdk 12.3
check libtheoraenc.1.dylib =================
  version 10.11
      sdk 12.3
check libuavs3d.dylib =================
  version 10.11
      sdk 12.3
check libuchardet.0.dylib =================
  version 10.11
      sdk 12.3
check libunibreak.5.dylib =================
  version 10.11
      sdk 12.3
check libvorbis.0.dylib =================
  version 10.11
      sdk 12.3
check libvorbisenc.2.dylib =================
  version 10.11
      sdk 12.3
check libvpx.8.dylib =================
  version 10.11
      sdk 12.3
check libwebp.7.dylib =================
  version 10.11
      sdk 12.3
check libwebpmux.3.dylib =================
  version 10.11
      sdk 12.3
check libxcb.1.dylib =================
    minos 13.0
      sdk 13.1
check libxml2.2.dylib =================
  version 10.11
      sdk 12.3
check libz.1.dylib =================
  version 10.11
      sdk 12.3
check libzimg.2.dylib =================
  version 10.11
      sdk 12.3
check libzvbi.0.dylib =================
  version 10.11
      sdk 12.3
```

有问题的是：libX11.6.dylib libXau.6.dylib libXdmcp.6.dylib libcjson.1.dylib libintl.8.dylib libmbedcrypto.13.dylib libpng16.16.dylib libxcb.1.dylib

需要对这几个文件重新进行编译。

**Comment by eko5624** [comment]
@acely  重新编译了一个，再帮忙测试下看能否运行：
[mpv-test.zip](https://github.com/eko5624/mpv-macos-intel/releases/download/2023-02-27/mpv-test.zip)

**Comment by acely** [comment]
这个编译好了很多了，首先在终端运行不报致命错误了，有了基本输出
```
Macbook:~ acely$ /Users/xxx/Downloads/0\ APPS/mpv.app/Contents/MacOS/mpv ; exit;
mpv 194dda-dirty Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Mon Feb 27 01:41:32 2023
libplacebo version: v5.229.1-293-gac45f213
FFmpeg version: git-2023-02-27-891ed24
FFmpeg library versions:
   libavutil       58.3.100
   libavcodec      60.5.100
   libavformat     60.4.100
   libswscale      7.2.100
   libavfilter     9.4.100
   libswresample   4.11.100

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

logout
```

但是直接双击app还是闪退，系统报告如下，太长所以放在附件了
[mpv-sys-log-20230227.txt](https://github.com/eko5624/mpv-macos-intel/files/10840427/mpv-sys-log-20230227.txt)

另外尝试在终端执行
`path/to/mpv xxx.mp4`
得到结果（只有一行）
`Segmentation fault: 11`

**Comment by eko5624** [comment]
难搞，我目前只能做到这一步了。用10.11的SDK编译也是通不过。我有个编译脚本，你可以在你本机上自己编译试试。
[mpv-build.sh.zip](https://github.com/eko5624/mpv-macos-intel/files/10840500/mpv-build.sh.zip)

**Comment by eko5624** [comment]
@acely 重新编译了一版，这次用了10.11的SDK，swift版本是3.1.1，希望这次不会报错。
https://github.com/eko5624/mpv-macos-intel/releases/download/2023-02-27/mpv-10.11.zip

**Comment by acely** [comment]
> @acely 重新编译了一版，这次用了10.11的SDK，swift版本是3.1.1，希望这次不会报错。 https://github.com/eko5624/mpv-macos-intel/releases/download/2023-02-27/mpv-10.11.zip

可以了！！牛逼！我要给你打赞助！

**Comment by eko5624** [comment]
![CDB8EE10E64090864EDDBEE1CC27D4F1](https://user-images.githubusercontent.com/84926938/222947735-f8224bdb-407d-4a61-8b13-119b00de0550.jpg)
非常感谢！😀
